name: "Tests"

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.15.4"
      - name: Install dependencies
        run: |
          yarn install --ignore-engines
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test -- --watchAll=false
      - name: check TS
        run: npx tsc --project ./tsconfig.json --noEmit
